name: "Setup Pipe"
description: "Checkout, Node, PNPM, Prisma generate"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Prisma generate
      run: npx prisma generate
      shell: bash
