
// eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6eyJ2YWx1ZSI6IjA4NjJhNjgxLWRiMDAtNGI0OS05NGRiLTk2MDlkODU4YzAxZSJ9fSwiaWF0IjoxNzU0MDM5NjMzfQ.Dn5fxf-pfHLG3xBtlbHh6QVhAfaUwQhfAB-sqRXFD5WjdSQd4O0geTN0QpOBENPMnV95A0MErEBVUGfnasGBAQddJzG1EgU4J0ZeES3-i6Oj-pn2ASv6f_RgF7yepzpgUEZy_iTuoQhvN6eq1WkhuaA95AIZVa-54mWUcBEdGFckYdUjbrAej6v6y0I9RJnnyM0KvnbBHioOOcgCCAoD50O5G6RVV_vC0ENWOPzny6gLmFIayx8-Q9a4A1UXmfYWoR5EwQbpSlxLYr0LGYK2feWXhLd0WQwN3aIbrLSB-X6F8pjoal5RyulUNJcWBxl6ezzELVeDOdFw0bCK_yUXCA

@baseUrl = http://localhost:3333

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Otavio",
  "email": "otavi1o@email.com",
  "password" : "otavio123",
  "sector" : "IT"
}

###

# @name authenticate_user

POST {{baseUrl}}/session
Content-Type: application/json

{
  "email": "otavio@email.com",
  "password" : "otavio123"
}