name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PUBLIC_KEY : ${{ secrets.PUBLIC_KEY }}
      PRIVATE_KEY : ${{ secrets.PRIVATE_KEY }}
    steps:
      - name: Importing setup pipe
        uses: ./.github/actions/setup-pipe

      - name: Importing setup database
        uses: ./.github/actions/setup-db

      - name: Run Unit tests
        run: pnpm run test

      - name: Run E2E tests
        run: pnpm run test:e2e

      - name: Stop Postgres
        if: always()
        run: docker compose down